x-bake:
  enabled: true

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - kanban-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - DJANGO_SETTINGS_MODULE=kanban_backend.settings
      - CORS_ORIGIN_WHITELIST=http://localhost,http://localhost:80,http://localhost:3000,http://frontend:3000
      - ALLOWED_HOSTS=localhost,backend,127.0.0.1,frontend
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_DEFAULT_REGION=us-west-2
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
    ports:
      - "8001:8000"
    volumes:
      - ./kanban_backend:/app/kanban_backend
    depends_on:
      - dynamodb-local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - kanban-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - REACT_APP_GRAPHQL_URL=http://localhost:8001/graphql
      - REACT_APP_API_URL=http://localhost:8001/graphql
      - WDS_SOCKET_PORT=0
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - kanban-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8002:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/shell/"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kanban-network

volumes:
  dynamodb_data:
    driver: local

networks:
  kanban-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16 